BOT_NAME = "RPA_FINANCEIRO_01"
MAX_RETRIES = 5
EXECUTION_TIMEOUT = 10
IS_PRODUCTION = True

print(f"Tipo BOT_NAME = ", type(BOT_NAME))
print(f"Tipo MAX_RETRIES = ", type(MAX_RETRIES))
print(f"Tipo EXECUTION_TIMEOUT = ", type(EXECUTION_TIMEOUT))
print(f"Tipo IS)PRODUCTION = ", type(IS_PRODUCTION))
